//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImage
    {
        public int imageId { get; set; }
        public string saveName { get; set; }
        public string extension { get; set; }
        public Nullable<int> width { get; set; }
        public Nullable<int> height { get; set; }
    }
}
