//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblImMessages
    {
        public string messageId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> groupId { get; set; }
        public string message { get; set; }
        public string fileName { get; set; }
        public int fromUser { get; set; }
        public int toUser { get; set; }
        public int readFlag { get; set; }
        public Nullable<System.DateTime> sendTime { get; set; }
        public Nullable<System.DateTime> receiveTime { get; set; }
    }
}
