//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoopPlan
    {
        public int loopId { get; set; }
        public Nullable<int> stationId { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> organizationId { get; set; }
        public Nullable<int> executionModeId { get; set; }
        public Nullable<int> eventOutputId { get; set; }
        public string eventOutput { get; set; }
        public Nullable<int> responsibleOrganization { get; set; }
        public Nullable<int> responsibleUser { get; set; }
        public Nullable<int> confirmOrganization { get; set; }
        public Nullable<int> confirmUser { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public string comment { get; set; }
        public string loopYear { get; set; }
        public string loopMonth { get; set; }
        public string loopWeek { get; set; }
        public string loopTime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> stop { get; set; }
        public Nullable<int> loopType { get; set; }
        public Nullable<bool> loopStatus { get; set; }
        public Nullable<int> importance { get; set; }
        public Nullable<int> urgency { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<int> unitTime { get; set; }
        public string keyword { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
        public bool deleteFlag { get; set; }
    }
}
