//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLoopplanSubmit
    {
        public int submitId { get; set; }
        public int loopId { get; set; }
        public Nullable<int> unitTime { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> completeStatus { get; set; }
        public Nullable<System.DateTime> executeTime { get; set; }
        public Nullable<System.DateTime> submitTime { get; set; }
        public Nullable<decimal> completeQuantity { get; set; }
        public Nullable<decimal> completeQuality { get; set; }
        public Nullable<decimal> completeTime { get; set; }
        public Nullable<System.DateTime> confirmTime { get; set; }
        public Nullable<int> haveStatistics { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
        public string result { get; set; }
        public Nullable<bool> isAttach { get; set; }
        public Nullable<bool> undo { get; set; }
    }
}
