//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLinkCondition
    {
        public int conditionId { get; set; }
        public Nullable<int> linkId { get; set; }
        public Nullable<int> type { get; set; }
        public string controlId { get; set; }
        public int condition { get; set; }
        public string value { get; set; }
        public Nullable<bool> testFlag { get; set; }
    }
}
