//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMonthPlanCompleteStatistics
    {
        public int userId { get; set; }
        public int organizationId { get; set; }
        public string statisticalTime { get; set; }
        public Nullable<int> planCount { get; set; }
        public Nullable<int> completeCount { get; set; }
        public Nullable<int> confirmedCount { get; set; }
        public Nullable<int> notComplateCount { get; set; }
        public Nullable<int> examineCount { get; set; }
        public Nullable<int> submitCount { get; set; }
        public Nullable<int> stopPlanCount { get; set; }
        public Nullable<int> timeOut { get; set; }
    }
}
