//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodeLink
    {
        public int linkId { get; set; }
        public Nullable<int> nodeEntry { get; set; }
        public Nullable<int> nodeExit { get; set; }
        public Nullable<int> templateId { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<bool> testFlag { get; set; }
    }
}
