//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNodeOperate
    {
        public int operateId { get; set; }
        public Nullable<int> nodeId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> condition { get; set; }
        public Nullable<int> countersign { get; set; }
        public Nullable<int> batchType { get; set; }
        public Nullable<int> batchCondition { get; set; }
        public Nullable<int> orderNum { get; set; }
        public Nullable<bool> testFlag { get; set; }
    }
}
