//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblNews
    {
        public int newId { get; set; }
        public Nullable<int> directoryId { get; set; }
        public string title { get; set; }
        public string contents { get; set; }
        public string summary { get; set; }
        public string titleImage { get; set; }
        public Nullable<bool> notice { get; set; }
        public Nullable<int> viewNum { get; set; }
        public Nullable<bool> isTop { get; set; }
        public string keyword { get; set; }
        public Nullable<bool> publish { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
