//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObjective
    {
        public int objectiveId { get; set; }
        public Nullable<int> parentObjective { get; set; }
        public Nullable<int> preObjective { get; set; }
        public bool displayChangeFlag { get; set; }
        public string objectiveName { get; set; }
        public Nullable<decimal> weight { get; set; }
        public Nullable<int> valueType { get; set; }
        public string objectiveValue { get; set; }
        public string expectedValue { get; set; }
        public string actualValue { get; set; }
        public Nullable<int> objectiveType { get; set; }
        public Nullable<int> responsibleOrg { get; set; }
        public Nullable<int> responsibleUser { get; set; }
        public Nullable<int> confirmUser { get; set; }
        public Nullable<int> authorizedUser { get; set; }
        public Nullable<int> checkType { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<System.DateTime> alarmTime { get; set; }
        public Nullable<System.DateTime> actualStartTime { get; set; }
        public Nullable<System.DateTime> actualEndTime { get; set; }
        public Nullable<decimal> completeQuantity { get; set; }
        public Nullable<decimal> completeQuality { get; set; }
        public Nullable<decimal> completeTime { get; set; }
        public Nullable<int> formula { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<decimal> maxValue { get; set; }
        public Nullable<decimal> minValue { get; set; }
        public int status { get; set; }
        public Nullable<int> priority { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> createSubmitTime { get; set; }
        public Nullable<System.DateTime> auditTime { get; set; }
        public Nullable<System.DateTime> resultSubmitTime { get; set; }
        public Nullable<System.DateTime> confirmTime { get; set; }
        public Nullable<bool> rpFlag { get; set; }
        public Nullable<bool> statisticFlag { get; set; }
        public string keyword { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
        public bool deleteFlag { get; set; }
    }
}
