//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObjectiveChange
    {
        public int changeId { get; set; }
        public int objectiveId { get; set; }
        public string objectiveName { get; set; }
        public bool objectiveNameUpdate { get; set; }
        public Nullable<decimal> weight { get; set; }
        public bool weightUpdate { get; set; }
        public Nullable<int> valueType { get; set; }
        public string objectiveValue { get; set; }
        public bool objectiveValueUpdate { get; set; }
        public string expectedValue { get; set; }
        public bool expectedValueUpdate { get; set; }
        public Nullable<int> objectiveType { get; set; }
        public Nullable<int> responsibleOrg { get; set; }
        public Nullable<int> responsibleUser { get; set; }
        public Nullable<int> confirmUser { get; set; }
        public Nullable<int> checkType { get; set; }
        public Nullable<decimal> bonus { get; set; }
        public bool bonusUpdate { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public bool startTimeUpdate { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public bool endTimeUpdate { get; set; }
        public Nullable<System.DateTime> alarmTime { get; set; }
        public bool alarmTimeUpdate { get; set; }
        public Nullable<int> progress { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
    }
}
