//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblObjectiveFormula
    {
        public int formulaId { get; set; }
        public int formulaNum { get; set; }
        public int objectiveId { get; set; }
        public int orderNum { get; set; }
        public Nullable<int> field { get; set; }
        public string operate { get; set; }
        public string numValue { get; set; }
        public Nullable<bool> valueType { get; set; }
    }
}
