//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlan
    {
        public int planId { get; set; }
        public Nullable<int> parentPlan { get; set; }
        public Nullable<int> projectId { get; set; }
        public Nullable<int> organizationId { get; set; }
        public Nullable<int> executionModeId { get; set; }
        public string eventOutput { get; set; }
        public Nullable<int> responsibleOrganization { get; set; }
        public Nullable<int> responsibleUser { get; set; }
        public Nullable<int> confirmOrganization { get; set; }
        public Nullable<int> confirmUser { get; set; }
        public Nullable<System.DateTime> startTime { get; set; }
        public Nullable<System.DateTime> endTime { get; set; }
        public Nullable<int> workTime { get; set; }
        public string comment { get; set; }
        public Nullable<int> alert { get; set; }
        public Nullable<int> importance { get; set; }
        public Nullable<int> urgency { get; set; }
        public Nullable<int> difficulty { get; set; }
        public Nullable<int> progress { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<decimal> completeQuantity { get; set; }
        public Nullable<decimal> completeQuality { get; set; }
        public Nullable<decimal> completeTime { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> stop { get; set; }
        public Nullable<int> initial { get; set; }
        public Nullable<bool> withSub { get; set; }
        public Nullable<bool> withFront { get; set; }
        public Nullable<bool> archive { get; set; }
        public Nullable<System.DateTime> archiveTime { get; set; }
        public Nullable<bool> autoStart { get; set; }
        public Nullable<System.DateTime> planGenerateTime { get; set; }
        public Nullable<System.DateTime> auditTime { get; set; }
        public Nullable<System.DateTime> submitTime { get; set; }
        public Nullable<System.DateTime> confirmTime { get; set; }
        public Nullable<int> meetingId { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
        public bool deleteFlag { get; set; }
        public Nullable<bool> rpFlag { get; set; }
        public Nullable<int> haveStatistics { get; set; }
        public string keyword { get; set; }
        public string result { get; set; }
        public Nullable<bool> isAttach { get; set; }
    }
}
