//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRewardPunish
    {
        public int rewardId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> type { get; set; }
        public Nullable<int> targetId { get; set; }
        public Nullable<int> timeoutDay { get; set; }
        public Nullable<int> deductionMode { get; set; }
        public Nullable<decimal> deductionNum { get; set; }
        public Nullable<System.DateTime> delayTime { get; set; }
        public Nullable<System.DateTime> statisticalTime { get; set; }
    }
}
