//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateControl
    {
        public int templateId { get; set; }
        public string controlId { get; set; }
        public string parentControl { get; set; }
        public int controlType { get; set; }
        public Nullable<int> require { get; set; }
        public string title { get; set; }
        public Nullable<int> size { get; set; }
        public Nullable<int> mutliSelect { get; set; }
        public Nullable<int> vertical { get; set; }
        public Nullable<int> lineType { get; set; }
        public Nullable<int> defaultRowNum { get; set; }
        public Nullable<int> columnStatistics { get; set; }
        public string color { get; set; }
        public string description { get; set; }
        public string moneyControl { get; set; }
        public Nullable<int> columnIndex { get; set; }
        public Nullable<int> rowIndex { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
    }
}
