//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateCategory
    {
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public string comment { get; set; }
        public Nullable<int> orderNum { get; set; }
        public Nullable<bool> system { get; set; }
        public Nullable<int> createUser { get; set; }
        public Nullable<System.DateTime> createTime { get; set; }
        public Nullable<int> updateUser { get; set; }
        public Nullable<System.DateTime> updateTime { get; set; }
        public Nullable<bool> deleteFlag { get; set; }
    }
}
