//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int userId { get; set; }
        public string userNumber { get; set; }
        public string userName { get; set; }
        public Nullable<int> authId { get; set; }
        public string randomKey { get; set; }
        public Nullable<int> defaultStationId { get; set; }
        public string imagePosition { get; set; }
        public string originalImage { get; set; }
        public string bigImage { get; set; }
        public string midImage { get; set; }
        public string smallImage { get; set; }
        public string password { get; set; }
        public Nullable<bool> sex { get; set; }
        public string nation { get; set; }
        public string political { get; set; }
        public Nullable<bool> marriage { get; set; }
        public string identityCard { get; set; }
        public string mobile1 { get; set; }
        public string mobile2 { get; set; }
        public string address { get; set; }
        public string workPlace { get; set; }
        public Nullable<System.DateTime> entryTime { get; set; }
        public Nullable<int> probationaryPeriod { get; set; }
        public Nullable<System.DateTime> positiveDate { get; set; }
        public Nullable<int> term { get; set; }
        public Nullable<System.DateTime> expiredDate { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<int> age { get; set; }
        public string nature { get; set; }
        public Nullable<int> province { get; set; }
        public Nullable<int> city { get; set; }
        public Nullable<int> district { get; set; }
        public string township { get; set; }
        public string school { get; set; }
        public string professional { get; set; }
        public Nullable<int> education { get; set; }
        public Nullable<System.DateTime> firstWork { get; set; }
        public string qualification { get; set; }
        public string cornet { get; set; }
        public string emergencyNumber { get; set; }
        public string bankCard { get; set; }
        public Nullable<int> workStatus { get; set; }
        public Nullable<System.DateTime> quitTime { get; set; }
        public Nullable<decimal> salary { get; set; }
        public Nullable<bool> admin { get; set; }
        public Nullable<bool> execution { get; set; }
        public Nullable<int> errorPassword { get; set; }
        public string nativePlace { get; set; }
        public string qq { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> internDate { get; set; }
        public Nullable<System.DateTime> probationDate { get; set; }
        public int createUser { get; set; }
        public System.DateTime createTime { get; set; }
        public int updateUser { get; set; }
        public System.DateTime updateTime { get; set; }
        public bool deleteFlag { get; set; }
        public Nullable<int> userType { get; set; }
    }
}
