//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.DAL
{
    using System;
    
    public partial class worktimeindex
    {
        public Nullable<decimal> totalwork { get; set; }
        public Nullable<decimal> totaleffective { get; set; }
        public Nullable<int> orgid { get; set; }
        public string orgname { get; set; }
        public Nullable<int> workdate { get; set; }
    }
}
