//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.Web.NotifyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NotifyServiceReference.ITaskRemindService")]
    public interface ITaskRemindService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskRemindService/Send", ReplyAction="http://tempuri.org/ITaskRemindService/SendResponse")]
        void Send(string msg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITaskRemindService/Send", ReplyAction="http://tempuri.org/ITaskRemindService/SendResponse")]
        System.Threading.Tasks.Task SendAsync(string msg);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITaskRemindServiceChannel : MB.Web.NotifyServiceReference.ITaskRemindService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TaskRemindServiceClient : System.ServiceModel.ClientBase<MB.Web.NotifyServiceReference.ITaskRemindService>, MB.Web.NotifyServiceReference.ITaskRemindService {
        
        public TaskRemindServiceClient() {
        }
        
        public TaskRemindServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TaskRemindServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskRemindServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TaskRemindServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Send(string msg) {
            base.Channel.Send(msg);
        }
        
        public System.Threading.Tasks.Task SendAsync(string msg) {
            return base.Channel.SendAsync(msg);
        }
    }
}
